# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 911f02cf15a0f8044b5ec4d95bb882827688648446387a92dde803708b92b8b6538c9c73ac196a8ea2d9a1f1e32ff9ec3d31a40638a6cc73da70d2c63c397313

test:
  secret_key_base: 33f24e2349b28a37611cd9c4363aea1a59881ffec2884ae87a5ae301d021611ccb0f75efe97022152787f0f741aa9eda024ac84e7284b1159b1d57cacf4a0da9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
